
import java.awt.*;   
import javax.swing.*;   
import java.io.*;   
/**  
 *  
 * @author  drawen  
 */   
public class MainWindow extends javax.swing.JFrame {   
    private JPanel contentPanel=new JPanel(new BorderLayout());   
    private Class newClass;   
    private Course corese;   
    private ScoreMenu scoreMenu;   
    /** Creates new form MainWindow */   
    public MainWindow() {   
        initComponents();   
        myInit();   
    }   
   
    /** This method is called from within the constructor to  
     * initialize the form.  
     * WARNING: Do NOT modify this code. The content of this method is  
     * always regenerated by the Form Editor.  
     */   
    // <editor-fold defaultstate="collapsed" desc=" 生成的代码 ">//GEN-BEGIN:initComponents   
    private void initComponents() {   
        try{   
            UIManager.setLookAndFeel(new com.sun.java.swing.plaf.windows.WindowsLookAndFeel());   
        }catch(Exception e){   
            System.out.println("设置失败");   
        }   
        jToolBarMenu = new javax.swing.JToolBar();   
        jButtonQuery = new javax.swing.JButton();   
        jButtonAdd = new javax.swing.JButton();   
        jButtonAnasys = new javax.swing.JButton();   
        jToolBarQuery = new javax.swing.JToolBar();   
        jButtonQueryStudent = new javax.swing.JButton();   
        jButtonQueryClass = new javax.swing.JButton();   
        jButtonQueryCourse = new javax.swing.JButton();   
        jToolBarAdd = new javax.swing.JToolBar();   
        jButtonAddStudent = new javax.swing.JButton();   
        jButtonAddClass = new javax.swing.JButton();   
        jButtonAddCourse = new javax.swing.JButton();   
        jButtonAddScore = new javax.swing.JButton();   
        jToolBarScoreAnasys = new javax.swing.JToolBar();   
        jButtonTextScore = new javax.swing.JButton();   
        jButtonColumnScore = new javax.swing.JButton();   
        jButtonCircleScore = new javax.swing.JButton();   
        jMenuBar1 = new javax.swing.JMenuBar();   
        jMenu1 = new javax.swing.JMenu();   
        jSeparator1 = new javax.swing.JSeparator();   
        jMenuItemExit = new javax.swing.JMenuItem();   
        jSeparator2 = new javax.swing.JSeparator();   
        jMenu2 = new javax.swing.JMenu();   
        jSeparator3 = new javax.swing.JSeparator();   
        jRadioButtonMenuItemMetal = new javax.swing.JRadioButtonMenuItem();   
        jRadioButtonMenuItemMotif = new javax.swing.JRadioButtonMenuItem();   
        jRadioButtonMenuItemWindows = new javax.swing.JRadioButtonMenuItem();   
        javax.swing.ButtonGroup group=new javax.swing.ButtonGroup();   
        group.add(jRadioButtonMenuItemMetal);   
        group.add(jRadioButtonMenuItemMotif);   
        group.add(jRadioButtonMenuItemWindows);   
        jSeparator4 = new javax.swing.JSeparator();   
        jMenu3 = new javax.swing.JMenu();   
        jSeparator5 = new javax.swing.JSeparator();   
        jMenuItemStudent = new javax.swing.JMenuItem();   
        jMenuItemCourse = new javax.swing.JMenuItem();   
        jMenuItemClass = new javax.swing.JMenuItem();   
        jMenuItemScoreMenu = new javax.swing.JMenuItem();   
        jSeparator6 = new javax.swing.JSeparator();   
        jMenu4 = new javax.swing.JMenu();   
        jSeparator7 = new javax.swing.JSeparator();   
        jMenuItemAboutSystem = new javax.swing.JMenuItem();   
        jMenuItemAboutAuthor = new javax.swing.JMenuItem();   
        jSeparator8 = new javax.swing.JSeparator();   
        jMenu5 = new javax.swing.JMenu();   
        jMenuCurrentTime = new javax.swing.JMenuItem();   
   
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);   
        setTitle("\u8003\u8bd5\u6210\u7ee9\u5206\u6790\u7a0b\u5e8f");   
        addWindowListener(new java.awt.event.WindowAdapter() {   
            public void windowClosing(java.awt.event.WindowEvent evt) {   
                windowClosingListener(evt);   
            }   
        });   
   
        jToolBarMenu.setBackground(new java.awt.Color(0, 51, 102));   
        jToolBarMenu.setPreferredSize(new java.awt.Dimension(161, 23));   
        jButtonQuery.setText("\u67e5\u8be2");   
        jButtonQuery.setToolTipText("\u67e5\u8be2");   
        jButtonQuery.addActionListener(new java.awt.event.ActionListener() {   
            public void actionPerformed(java.awt.event.ActionEvent evt) {   
                queryButtonActionListener(evt);   
            }   
        });   
   
        jToolBarMenu.add(jButtonQuery);   
   
        jButtonAdd.setText("\u589e\u52a0");   
        jButtonAdd.setToolTipText("\u589e\u52a0");   
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {   
            public void actionPerformed(java.awt.event.ActionEvent evt) {   
                addButtonActionListener(evt);   
            }   
        });   
   
        jToolBarMenu.add(jButtonAdd);   
   
        jButtonAnasys.setText("\u6210\u7ee9\u5206\u6790");   
        jButtonAnasys.setToolTipText("\u6210\u7ee9\u5206\u6790");   
        jButtonAnasys.addActionListener(new java.awt.event.ActionListener() {   
            public void actionPerformed(java.awt.event.ActionEvent evt) {   
                scoreAnasysButtonActionListener(evt);   
            }   
        });   
   
        jToolBarMenu.add(jButtonAnasys);   
   
        jButtonQueryStudent.setText("\u67e5\u8be2\u5b66\u751f\u4fe1\u606f");   
        jButtonQueryStudent.addActionListener(new java.awt.event.ActionListener() {   
            public void actionPerformed(java.awt.event.ActionEvent evt) {   
                queryStudentButtonActionListener(evt);   
            }   
        });   
   
        jToolBarQuery.add(jButtonQueryStudent);   
   
        jButtonQueryClass.setText("\u67e5\u8be2\u73ed\u7ea7\u4fe1\u606f");   
        jButtonQueryClass.addActionListener(new java.awt.event.ActionListener() {   
            public void actionPerformed(java.awt.event.ActionEvent evt) {   
                queryClassButtonActionListener(evt);   
            }   
        });   
   
        jToolBarQuery.add(jButtonQueryClass);   
   
        jButtonQueryCourse.setText("\u67e5\u8be2\u8bfe\u7a0b\u4fe1\u606f");   
        jButtonQueryCourse.addActionListener(new java.awt.event.ActionListener() {   
            public void actionPerformed(java.awt.event.ActionEvent evt) {   
                queryCourseButtonActionListener(evt);   
            }   
        });   
   
        jToolBarQuery.add(jButtonQueryCourse);   
   
        jButtonAddStudent.setText("\u589e\u52a0\u5b66\u751f\u4fe1\u606f");   
        jButtonAddStudent.addActionListener(new java.awt.event.ActionListener() {   
            public void actionPerformed(java.awt.event.ActionEvent evt) {   
                addStudentButtonActionListener(evt);   
            }   
        });   
   
        jToolBarAdd.add(jButtonAddStudent);   
   
        jButtonAddClass.setText("\u589e\u52a0\u73ed\u7ea7\u4fe1\u606f");   
        jButtonAddClass.addActionListener(new java.awt.event.ActionListener() {   
            public void actionPerformed(java.awt.event.ActionEvent evt) {   
                addClassButtonActionListener(evt);   
            }   
        });   
   
        jToolBarAdd.add(jButtonAddClass);   
   
        jButtonAddCourse.setText("\u589e\u52a0\u8bfe\u7a0b\u4fe1\u606f");   
        jButtonAddCourse.addActionListener(new java.awt.event.ActionListener() {   
            public void actionPerformed(java.awt.event.ActionEvent evt) {   
                addCourseButtonActionListener(evt);   
            }   
        });   
   
        jToolBarAdd.add(jButtonAddCourse);   
   
        jButtonAddScore.setText("\u589e\u52a0\u5b66\u751f\u6210\u7ee9");   
        jButtonAddScore.addActionListener(new java.awt.event.ActionListener() {   
            public void actionPerformed(java.awt.event.ActionEvent evt) {   
                addStudentScoreButtonActionListener(evt);   
            }   
        });   
   
        jToolBarAdd.add(jButtonAddScore);   
   
        jButtonTextScore.setText("\u6210\u7ee9\u6587\u5b57\u5206\u6790");   
        jToolBarScoreAnasys.add(jButtonTextScore);   
   
        jButtonColumnScore.setText("\u6210\u7ee9\u67f1\u72b6\u5206\u6790");   
        jToolBarScoreAnasys.add(jButtonColumnScore);   
   
        jButtonCircleScore.setText("\u6210\u7ee9\u997c\u72b6\u5206\u6790");   
        jToolBarScoreAnasys.add(jButtonCircleScore);   
   
        jMenu1.setText("\u9000\u51fa");   
        jMenu1.setToolTipText("\u9000\u51fa\u7cfb\u7edf");   
        jSeparator1.setBackground(new java.awt.Color(102, 102, 0));   
        jMenu1.add(jSeparator1);   
   
        jMenuItemExit.setText("\u9000\u51fa");   
        jMenuItemExit.setToolTipText("\u9000\u51fa\u7cfb\u7edf");   
        jMenuItemExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));   
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {   
            public void actionPerformed(java.awt.event.ActionEvent evt) {   
                jMenuItemExitActionListener(evt);   
            }   
        });   
   
        jMenu1.add(jMenuItemExit);   
   
        jMenu1.add(jSeparator2);   
   
        jMenuBar1.add(jMenu1);   
   
        jMenu2.setText("\u663e\u793a\u98ce\u683c");   
        jMenu2.add(jSeparator3);   
   
        jRadioButtonMenuItemMetal.setText("Metal");   
        jRadioButtonMenuItemMetal.setToolTipText("\u91d1\u5c5e\u98ce\u683c");   
        jRadioButtonMenuItemMetal.addActionListener(new java.awt.event.ActionListener() {   
            public void actionPerformed(java.awt.event.ActionEvent evt) {   
                jRadioButtonMenuItemMetal(evt);   
            }   
        });   
   
        jMenu2.add(jRadioButtonMenuItemMetal);   
   
        jRadioButtonMenuItemMotif.setText("Motif");   
        jRadioButtonMenuItemMotif.setToolTipText("\u4e3b\u9898\u98ce\u683c");   
        jRadioButtonMenuItemMotif.addActionListener(new java.awt.event.ActionListener() {   
            public void actionPerformed(java.awt.event.ActionEvent evt) {   
                jRadioButtonMenuItemMotif(evt);   
            }   
        });   
   
        jMenu2.add(jRadioButtonMenuItemMotif);   
   
        jRadioButtonMenuItemWindows.setSelected(true);   
        jRadioButtonMenuItemWindows.setText("Windows");   
        jRadioButtonMenuItemWindows.setToolTipText("\u89c6\u7a97\u98ce\u683c");   
        jRadioButtonMenuItemWindows.addActionListener(new java.awt.event.ActionListener() {   
            public void actionPerformed(java.awt.event.ActionEvent evt) {   
                jRadioButtonMenuItemWindows(evt);   
            }   
        });   
   
        jMenu2.add(jRadioButtonMenuItemWindows);   
   
        jMenu2.add(jSeparator4);   
   
        jMenuBar1.add(jMenu2);   
   
        jMenu3.setText("\u7cfb\u7edf\u6587\u4ef6");   
        jMenu3.add(jSeparator5);   
   
        jMenuItemStudent.setText("\u5b66\u751f\u6587\u4ef6");   
        jMenuItemStudent.setToolTipText("\u7cfb\u7edf\u4e2d\u8bb0\u5f55\u7684\u5b66\u751f\u4fe1\u606f");   
        jMenuItemStudent.addActionListener(new java.awt.event.ActionListener() {   
            public void actionPerformed(java.awt.event.ActionEvent evt) {   
                jMenuItemStudentActionListener(evt);   
            }   
        });   
   
        jMenu3.add(jMenuItemStudent);   
   
        jMenuItemCourse.setText("\u8bfe\u7a0b\u6587\u4ef6");   
        jMenuItemCourse.setToolTipText("\u7cfb\u7edf\u4e2d\u8bb0\u5f55\u7684\u8bfe\u7a0b\u4fe1\u606f");   
        jMenuItemCourse.addActionListener(new java.awt.event.ActionListener() {   
            public void actionPerformed(java.awt.event.ActionEvent evt) {   
                jMenuItemCourseActionListener(evt);   
            }   
        });   
   
        jMenu3.add(jMenuItemCourse);   
   
        jMenuItemClass.setText("\u73ed\u7ea7\u6587\u4ef6");   
        jMenuItemClass.setToolTipText("\u7cfb\u7edf\u4e2d\u8bb0\u5f55\u7684\u73ed\u7ea7\u4fe1\u606f");   
        jMenuItemClass.addActionListener(new java.awt.event.ActionListener() {   
            public void actionPerformed(java.awt.event.ActionEvent evt) {   
                jMenuItemClassActionListener(evt);   
            }   
        });   
   
        jMenu3.add(jMenuItemClass);   
   
        jMenuItemScoreMenu.setText("\u6210\u7ee9\u5355\u6587\u4ef6");   
        jMenuItemScoreMenu.setToolTipText("\u7cfb\u7edf\u4e2d\u8bb0\u5f55\u7684\u6210\u7ee9\u5355\u4fe1\u606f");   
        jMenuItemScoreMenu.addActionListener(new java.awt.event.ActionListener() {   
            public void actionPerformed(java.awt.event.ActionEvent evt) {   
                jMenuItemScoreMenuActionListener(evt);   
            }   
        });   
   
        jMenu3.add(jMenuItemScoreMenu);   
   
        jMenu3.add(jSeparator6);   
   
        jMenuBar1.add(jMenu3);   
   
        jMenu4.setText("\u9009\u9879");   
        jMenu4.add(jSeparator7);   
   
        jMenuItemAboutSystem.setText("\u5173\u4e8e\u7cfb\u7edf");   
        jMenuItemAboutSystem.setToolTipText("\u7b80\u4ecb\u7cfb\u7edf\u7684\u529f\u80fd");   
        jMenuItemAboutSystem.addActionListener(new java.awt.event.ActionListener() {   
            public void actionPerformed(java.awt.event.ActionEvent evt) {   
                jMenuItemAboutSystemActionListener(evt);   
            }   
        });   
   
        jMenu4.add(jMenuItemAboutSystem);   
   
        jMenuItemAboutAuthor.setText("\u5173\u4e8e\u4f5c\u8005");   
        jMenuItemAboutAuthor.setToolTipText("\u4ecb\u7ecd\u4f5c\u8005\u7684\u57fa\u672c\u4fe1\u606f");   
        jMenuItemAboutAuthor.addActionListener(new java.awt.event.ActionListener() {   
            public void actionPerformed(java.awt.event.ActionEvent evt) {   
                jMenuItemAboutAuthorActionListener(evt);   
            }   
        });   
   
        jMenu4.add(jMenuItemAboutAuthor);   
   
        jMenu4.add(jSeparator8);   
   
        jMenuBar1.add(jMenu4);   
   
        jMenu5.setText("\u5f53\u524d\u65f6\u95f4");   
        jMenuCurrentTime.setText("\u663e\u793a\u5f53\u524d\u65f6\u95f4");   
        jMenuCurrentTime.addActionListener(new java.awt.event.ActionListener() {   
            public void actionPerformed(java.awt.event.ActionEvent evt) {   
                jMenuCurrentTimeActionListener(evt);   
            }   
        });   
   
        jMenu5.add(jMenuCurrentTime);   
   
        jMenuBar1.add(jMenu5);   
   
        setJMenuBar(jMenuBar1);   
   
        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());   
        getContentPane().setLayout(layout);   
        layout.setHorizontalGroup(   
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)   
            .add(layout.createSequentialGroup()   
                .addContainerGap()   
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)   
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jToolBarQuery, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)   
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jToolBarMenu, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 613, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)   
                    .add(jToolBarAdd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 603, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)   
                    .add(jToolBarScoreAnasys, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 603, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))   
                .addContainerGap())   
        );   
        layout.setVerticalGroup(   
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)   
            .add(layout.createSequentialGroup()   
                .addContainerGap()   
                .add(jToolBarMenu, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)   
                .add(25, 25, 25)   
                .add(jToolBarQuery, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)   
                .add(12, 12, 12)   
                .add(jToolBarAdd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)   
                .add(15, 15, 15)   
                .add(jToolBarScoreAnasys, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)   
                .add(245, 245, 245))   
        );   
        pack();   
    }// </editor-fold>//GEN-END:initComponents   
    public void myInit(){           
        initDataFile(Student.STUDENT_FILE);   
        initDataFile(Class.CLASS_FILE);   
        initDataFile(Course.COURSE_FILE);   
        initDataFile(ScoreMenu.SCORE_MENU_FILE);   
        remove(jToolBarMenu);   
        remove(jToolBarQuery);   
        remove(jToolBarAdd);   
        remove(jToolBarScoreAnasys);   
        JPanel jpanel=new JPanel(new BorderLayout());   
        jpanel.add(jToolBarMenu,BorderLayout.SOUTH);   
        jpanel.add(contentPanel,BorderLayout.CENTER);   
        setLayout(new BorderLayout());   
        getContentPane().add(jpanel,BorderLayout.CENTER);   
    }   
    private void jMenuCurrentTimeActionListener(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCurrentTimeActionListener   
        CurrentTime time=new CurrentTime("当前时间");   
        time.setSize(520,400);   
        time.setVisible(true);   
    }//GEN-LAST:event_jMenuCurrentTimeActionListener   
   
    private void jMenuItemAboutAuthorActionListener(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutAuthorActionListener   
        String text="指导老师：肖磊\n作者：张文龙\n年级：2005级\n专业班级：计算机科学与技术3班\n邮箱：zhang_wen_long@126.com";   
        JOptionPane.showMessageDialog(null,text,"关于作者",JOptionPane.WARNING_MESSAGE);   
    }//GEN-LAST:event_jMenuItemAboutAuthorActionListener   
   
    private void jMenuItemAboutSystemActionListener(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutSystemActionListener   
        String text="系统可以分为三大操作模块：\n查询模块，增加模块，成绩分析模块\n每个模块里面包括学生操作，班级操作，" +   
                "课程操作，成绩单操作\n用户可以通过窗口最下面的工具栏选择相应模块\n在每个模块里面选择相应功能\n";   
        JOptionPane.showMessageDialog(null,text,"关于系统",JOptionPane.WARNING_MESSAGE);   
    }//GEN-LAST:event_jMenuItemAboutSystemActionListener   
   
    private void jMenuItemExitActionListener(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionListener   
        int select=JOptionPane.showConfirmDialog(null,"确定退出系统","确定",JOptionPane.OK_CANCEL_OPTION);   
        if(select==0)   
            System.exit(0);   
    }//GEN-LAST:event_jMenuItemExitActionListener   
   
    private void windowClosingListener(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowClosingListener   
        int select=JOptionPane.showConfirmDialog(null,"确定退出系统","确定",JOptionPane.OK_CANCEL_OPTION);   
        if(select==0)   
            System.exit(0);   
    }//GEN-LAST:event_windowClosingListener   
    public static void initDataFile(String fileName){   
        File file=new File(fileName);   
        try{   
            if(!file.exists())   
                file.createNewFile();   
        }catch(Exception e){}   
    }   
   
    private void jRadioButtonMenuItemWindows(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItemWindows   
        try{   
            UIManager.setLookAndFeel(new com.sun.java.swing.plaf.windows.WindowsLookAndFeel());   
        }catch(Exception e){   
            System.out.println("设置失败");   
        }   
    }//GEN-LAST:event_jRadioButtonMenuItemWindows   
   
    private void jRadioButtonMenuItemMotif(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItemMotif   
        try{   
            UIManager.setLookAndFeel(new com.sun.java.swing.plaf.motif.MotifLookAndFeel());   
        }catch(Exception e){   
            System.out.println("设置失败");   
        }   
    }//GEN-LAST:event_jRadioButtonMenuItemMotif   
   
    private void jRadioButtonMenuItemMetal(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItemMetal   
        try{   
            UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());   
        }catch(Exception e){   
            System.out.println("设置失败");   
        }   
    }//GEN-LAST:event_jRadioButtonMenuItemMetal   
   
    private void jMenuItemScoreMenuActionListener(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemScoreMenuActionListener   
        ScoreMenu[] scoreMenu=ScoreMenu.loadFile();   
        Class tempClass;   
        Course course;   
        int[] testTime;   
        int number;   
        long[] id;   
        float[] score;   
        int count=0;   
        for(int i=0;i<scoreMenu.length;i++)   
            if(scoreMenu[i]!=null)   
                count++;   
        String text="成绩单信息文件中总共有"+count+"个成绩单，具体如下：\n";   
        for(int i=0;i<count;i++){   
            tempClass=scoreMenu[i].getClassOfScoreMenu();   
            course=scoreMenu[i].getCourse();   
            testTime=scoreMenu[i].getTestTime();   
            number=scoreMenu[i].getNumberOfAttendTestStudent();   
            id=scoreMenu[i].getIdOfStudents();   
            score=scoreMenu[i].getScoreOfTest();   
            text=text+"\n课程编号："+course.getId()+"\t课程名称："+course.getName()+   
                    "\n登记时间："+testTime[0]+"年"+testTime[1]+"月"+testTime[2]+"日"+   
                    testTime[3]+"小时"+testTime[4]+"分钟\n班级信息：\n年级："+tempClass.getGrade()+   
                    "\t专业："+tempClass.getMajor()+"\t班号："+tempClass.getClassNumber()+   
                    "\t班级人数："+tempClass.getStudentNumber()+"\t考试人数"+number+"\n具体分数如下：\n" +   
                    "学号\t分数\n";   
            for(int j=0;j<number;j++)   
                text=text+id[j]+"\t"+score[j]+"\n";   
        }   
        FilePanel panel=new FilePanel("成绩单信息文件",text);   
        panel.setSize(520,400);   
        panel.setVisible(true);   
    }//GEN-LAST:event_jMenuItemScoreMenuActionListener   
   
    private void jMenuItemClassActionListener(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClassActionListener   
        Class[] array=Class.loadFile();   
        Student[] student;   
        int count=0;   
        for(int i=0;i<array.length;i++)   
            if(array[i]!=null)   
                count++;   
        String text="班级文件中总共有"+count+"个班级的信息，具体如下：\n";   
        for(int i=0;i<count;i++){   
            text=text+"\n年级："+array[i].getGrade()+"\n专业："+array[i].getMajor()+   
                    "\n班级号："+array[i].getClassNumber()+"\n班级人数："+array[i].getStudentNumber()+   
                    "\n学生信息具体如下：\n姓名\t学号\n";   
            student=array[i].getStudents();   
            int num=0;   
            for(int j=0;j<student.length;j++)   
                if(student[j]!=null)   
                    num++;   
            for(int j=0;j<num;j++)   
                text=text+student[j].getId()+"\t"+student[j].getName()+"\n";   
            text+="\n";   
        }   
        FilePanel panel=new FilePanel("班级信息文件",text);   
        panel.setSize(520,400);   
        panel.setVisible(true);   
    }//GEN-LAST:event_jMenuItemClassActionListener   
   
    private void jMenuItemCourseActionListener(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCourseActionListener   
        Course[] course=Course.loadFile();   
        int count=0;   
        for(int i=0;i<course.length;i++)   
            if(course[i]!=null)   
                count++;   
        String text="课程文件中总共有"+count+"个课程的信息，具体如下：\n";   
        for(int i=0;i<count;i++)   
            text=text+"\n课程编号："+course[i].getId()+"\n课程名称："+course[i].getName()+   
                    "\n学分："+course[i].getCredit()+"\n学分："+course[i].getPeriod()+"\n";   
        FilePanel panel=new FilePanel("课程信息文件",text);   
        panel.setSize(520,400);   
        panel.setVisible(true);   
    }//GEN-LAST:event_jMenuItemCourseActionListener   
   
    private void jMenuItemStudentActionListener(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemStudentActionListener   
        Student[] student=Student.loadFile();   
        int count=0;   
        for(int i=0;i<student.length;i++)   
            if(student[i]!=null)   
                count++;   
        String text="学生文件中总共有"+count+"个学生的信息，具体如下：\n姓名\t学号\n";   
        for(int i=0;i<count;i++)   
            text=text+student[i].getName()+"\t"+student[i].getId()+"\n";   
        FilePanel panel=new FilePanel("学生信息文件",text);   
        panel.setSize(520,400);   
        panel.setVisible(true);   
    }//GEN-LAST:event_jMenuItemStudentActionListener   
   
    private void addStudentScoreButtonActionListener(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentScoreButtonActionListener   
        Component []components=contentPanel.getComponents();   
        for(int i=0;i<components.length;i++)   
            contentPanel.remove(components[i]);   
        contentPanel.repaint();   
        contentPanel.add(new AddScoreMenuJPanel());   
        contentPanel.add(jToolBarAdd,BorderLayout.NORTH);   
        contentPanel.validate();   
    }//GEN-LAST:event_addStudentScoreButtonActionListener   
   
    private void queryClassButtonActionListener(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queryClassButtonActionListener   
        Component []components=contentPanel.getComponents();   
        for(int i=0;i<components.length;i++)   
            contentPanel.remove(components[i]);   
        contentPanel.repaint();   
        contentPanel.add(new QueryClassJPanel());   
        contentPanel.add(jToolBarQuery,BorderLayout.NORTH);   
        contentPanel.validate();           
    }//GEN-LAST:event_queryClassButtonActionListener   
   
    private void addClassButtonActionListener(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClassButtonActionListener   
        Component []components=contentPanel.getComponents();   
        for(int i=0;i<components.length;i++)   
            contentPanel.remove(components[i]);   
        contentPanel.repaint();   
        contentPanel.add(new AddClassJPanel());   
        contentPanel.add(jToolBarAdd,BorderLayout.NORTH);   
        contentPanel.validate();   
    }//GEN-LAST:event_addClassButtonActionListener   
   
    private void queryStudentButtonActionListener(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queryStudentButtonActionListener   
        Component []components=contentPanel.getComponents();   
        for(int i=0;i<components.length;i++)   
            contentPanel.remove(components[i]);   
        contentPanel.repaint();   
        contentPanel.add(new QueryStudentJPanel());   
        contentPanel.add(jToolBarQuery,BorderLayout.NORTH);   
        contentPanel.validate();           
    }//GEN-LAST:event_queryStudentButtonActionListener   
   
    private void addStudentButtonActionListener(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentButtonActionListener   
        Component []components=contentPanel.getComponents();   
        for(int i=0;i<components.length;i++)   
            contentPanel.remove(components[i]);   
        contentPanel.repaint();   
        contentPanel.add(new AddStudentJPanel());   
        contentPanel.add(jToolBarAdd,BorderLayout.NORTH);   
        contentPanel.validate();    
    }//GEN-LAST:event_addStudentButtonActionListener   
   
    private void queryCourseButtonActionListener(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queryCourseButtonActionListener   
        Component []components=contentPanel.getComponents();   
        for(int i=0;i<components.length;i++)   
            contentPanel.remove(components[i]);   
        contentPanel.repaint();   
        contentPanel.add(new QueryCourseJPanel());   
        contentPanel.add(jToolBarQuery,BorderLayout.NORTH);   
        contentPanel.validate();    
    }//GEN-LAST:event_queryCourseButtonActionListener   
   
    private void addCourseButtonActionListener(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseButtonActionListener   
        Component []components=contentPanel.getComponents();   
        for(int i=0;i<components.length;i++)   
            contentPanel.remove(components[i]);   
        contentPanel.repaint();   
        contentPanel.add(new AddCourseJPanel());   
        contentPanel.add(jToolBarAdd,BorderLayout.NORTH);   
        contentPanel.validate();    
    }//GEN-LAST:event_addCourseButtonActionListener   
   
    private void scoreAnasysButtonActionListener(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreAnasysButtonActionListener   
        Component []array=contentPanel.getComponents();   
        for(int i=0;i<array.length;i++){   
                contentPanel.remove(array[i]);   
        }   
        contentPanel.repaint();   
        contentPanel.add(new QueryScoreMenuJPanel(jButtonTextScore,jButtonColumnScore,jButtonCircleScore));   
        contentPanel.add(jToolBarScoreAnasys,BorderLayout.NORTH);   
        this.validate();   
    }//GEN-LAST:event_scoreAnasysButtonActionListener   
   
    private void addButtonActionListener(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionListener   
        Component []array=contentPanel.getComponents();   
        for(int i=0;i<array.length;i++){   
                contentPanel.remove(array[i]);   
        }           
        contentPanel.repaint();   
        contentPanel.add(jToolBarAdd,BorderLayout.NORTH);   
        this.validate();   
    }//GEN-LAST:event_addButtonActionListener   
   
    private void queryButtonActionListener(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queryButtonActionListener   
        Component []array=contentPanel.getComponents();   
        for(int i=0;i<array.length;i++){   
                contentPanel.remove(array[i]);   
        }           
        contentPanel.repaint();   
        contentPanel.add(jToolBarQuery,BorderLayout.NORTH);   
        this.validate();   
    }//GEN-LAST:event_queryButtonActionListener   
       
       
    // 变量声明 - 不进行修改//GEN-BEGIN:variables   
    private javax.swing.JButton jButtonAdd;   
    private javax.swing.JButton jButtonAddClass;   
    private javax.swing.JButton jButtonAddCourse;   
    private javax.swing.JButton jButtonAddScore;   
    private javax.swing.JButton jButtonAddStudent;   
    private javax.swing.JButton jButtonAnasys;   
    private javax.swing.JButton jButtonCircleScore;   
    private javax.swing.JButton jButtonColumnScore;   
    private javax.swing.JButton jButtonQuery;   
    private javax.swing.JButton jButtonQueryClass;   
    private javax.swing.JButton jButtonQueryCourse;   
    private javax.swing.JButton jButtonQueryStudent;   
    private javax.swing.JButton jButtonTextScore;   
    private javax.swing.JMenu jMenu1;   
    private javax.swing.JMenu jMenu2;   
    private javax.swing.JMenu jMenu3;   
    private javax.swing.JMenu jMenu4;   
    private javax.swing.JMenu jMenu5;   
    private javax.swing.JMenuBar jMenuBar1;   
    private javax.swing.JMenuItem jMenuCurrentTime;   
    private javax.swing.JMenuItem jMenuItemAboutAuthor;   
    private javax.swing.JMenuItem jMenuItemAboutSystem;   
    private javax.swing.JMenuItem jMenuItemClass;   
    private javax.swing.JMenuItem jMenuItemCourse;   
    private javax.swing.JMenuItem jMenuItemExit;   
    private javax.swing.JMenuItem jMenuItemScoreMenu;   
    private javax.swing.JMenuItem jMenuItemStudent;   
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemMetal;   
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemMotif;   
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemWindows;   
    private javax.swing.JSeparator jSeparator1;   
    private javax.swing.JSeparator jSeparator2;   
    private javax.swing.JSeparator jSeparator3;   
    private javax.swing.JSeparator jSeparator4;   
    private javax.swing.JSeparator jSeparator5;   
    private javax.swing.JSeparator jSeparator6;   
    private javax.swing.JSeparator jSeparator7;   
    private javax.swing.JSeparator jSeparator8;   
    private javax.swing.JToolBar jToolBarAdd;   
    private javax.swing.JToolBar jToolBarMenu;   
    private javax.swing.JToolBar jToolBarQuery;   
    private javax.swing.JToolBar jToolBarScoreAnasys;   
    // 变量声明结束//GEN-END:variables   
    class FilePanel extends JFrame{   
        FilePanel(String title,String text){   
            setTitle(title);   
            JEditorPane pane=new JEditorPane();   
            pane.setEditable(false);   
            pane.setText(text);   
            JScrollPane jscrollPane=new JScrollPane();   
            jscrollPane.setViewportView(pane);   
            add(jscrollPane);   
        }   
    }   
}   
